context.properties = {
    default.clock.quantum = 1024
    default.clock.min-quantum = 1024
}

context.objects = [
    { factory = adapter
        args = {
            factory.name           = api.alsa.pcm.sink
            node.name              = "my-default-sink"
            node.description       = "my-default-sink"
            media.class            = "Audio/Sink"
            api.alsa.path          = "hw:0,1"
            audio.channels         = 2
        }
    }
]

context.modules = [
{   name = libpipewire-module-combine-stream
    args = {
        combine.mode = sink
        node.name = "my-combine-sink"
        node.description = "my-combine-sink"
        combine.latency-compensate = true
        combine.props = {
            audio.position = [ FL FR ]
        }
        stream.props = {
            stream.dont-remix = true
        }
        stream.rules = [
            {
                matches = [
                    {
                        media.class = "Audio/Sink"
                        node.name = "my-default-sink"
                    }
                ]
                actions = {
                    create-stream = {
                        combine.audio.position = [ FL FR ]
                        audio.position = [ FL FR ]
                    }
                }
            }
        ]
    }
}
]



