#!/bin/sh
#
# Starts pulseaudio.
#

start() {
	printf "Starting pulseaudio: "
	umask 077

	/usr/bin/pulseaudio \
			--daemonize \
			--disallow-module-loading \
			--disallow-exit \
			--exit-idle-time=-1 \
			--disable-shm \
			--log-level=info
}

stop() {
	printf "Stopping pulseaudio: "
	killall pulseaudio 2>/dev/null
	echo "OK"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start)
        start
        ;;
	stop)
        stop
        ;;
	restart|reload)
        restart
        ;;
	*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?