################################################################################
################################################################################
##
## Various utility functions for linux kernel
##
################################################################################
################################################################################
define KCONFIG_ENABLE_OPT # (option, file)
	sed -i -e "/\\<$(1)\\>/d" $(2)
	echo '$(1)=y' >> $(2)
endef

define KCONFIG_SET_OPT # (option, value, file)
	sed -i -e "/\\<$(1)\\>/d" $(3)
	echo '$(1)=$(2)' >> $(3)
endef

define KCONFIG_DISABLE_OPT # (option, file)
	sed -i -e "/\\<$(1)\\>/d" $(2)
	echo '# $(1) is not set' >> $(2)
endef

define KCONFIG_DISABLE_OPT_LIST # (options, file)
	for kernel_item in $$(echo $(1)); 	do \
		sed -i -e "/\\<$$kernel_item\\>/d" $(2); \
		echo "# $$kernel_item is not set" >> $(2); \
	done
endef

define KCONFIG_ENABLE_OPT_LIST # (options, file)
	for kernel_item in $$(echo $(1)); 	do \
		sed -i -e "/\\<$$kernel_item\\>/d" $(2); \
		echo "$$kernel_item=y" >> $(2); \
	done
endef

define KCONFIG_SET_OPT_LIST # (options, file)
	for kernel_set in $$(echo $(1)); 	do \
		kernel_item=$$(echo $$kernel_set| cut -d'=' -f1); \
		sed -i -e "/\\<$$kernel_item\\>/d" $(2); \
		echo "$$kernel_set" >> $(2); \
	done
endef

define KCONFIG_SET_TRISTATE_OPT # (option, value[m,y,n], file)
	$(if $(filter $(2), n),$(call KCONFIG_DISABLE_OPT,$(1),$(3)),$(call KCONFIG_SET_OPT,$(1),$(2),$(3)))
endef

define KCONFIG_SET_BOOL_OPT # (option, value[m,y,n], file)
	$(if $(filter $(2), m),$(call KCONFIG_SET_TRISTATE_OPT,$(1),y,$(3)),
			$(call KCONFIG_SET_TRISTATE_OPT,$(1),$(2),$(3)))
endef

CUSTOMIZE_KERNEL_ENABLE_OPT_LIST="CONFIG_FUSE_FS CONFIG_NFS_FS CONFIG_NFS_V2 CONFIG_NFS_V3 CONFIG_NFS_V4 CONFIG_NFS_COMMON"
CUSTOMIZE_KERNEL_DISABLE_OPT_LIST=""
ifneq ($(filter C302X_N2 C302X_N3 C308L C308L_N2N3, $(BR2_AML_C3_PLATFORM)),)
CUSTOMIZE_KERNEL_SET_OPT_LIST=""
else ifneq ($(filter C302X_N2_DoorBell C302X_N3_DoorBell, $(BR2_AML_C3_PLATFORM)),)
CUSTOMIZE_KERNEL_SET_OPT_LIST="CONFIG_FUSE_FS=n CONFIG_NTFS_FS=n CONFIG_OVERLAY_FS=n"
else ifeq ($(BR2_AML_C3_PLATFORM), C302X_EMMC)
CUSTOMIZE_KERNEL_SET_OPT_LIST="CONFIG_AMLOGIC_NAND=n"
endif

define AML_KERNEL_GENERAL_CONFIGURATION # (file)
	$(call AML_KERENL_MODULE_ALWAYS_BUILD_IN,$(1))

	$(if $(filter $(BR2_AML_C3_PLATFORM), C302X_N2_DoorBell C302X_N3_DoorBell),$(call AML_KERNEL_MODULE_CONFIG_SET_OPT,m,$(1)),
		$(if $(filter $(BR2_AML_C3_ROOTFS_MEDIUM), FLASH),$(call AML_KERENL_MODULE_BUILD_IN,$(1)) 	$(call AML_KERNEL_MODULE_CONFIG_SET_OPT,y,$(1)),
		$(call AML_KERNEL_MODULE_CONFIG_SET_OPT,m,$(1))))

	$(call AML_FS_CONFIG_SET_OPT,y,$(1))
	$(if $(filter $(BR2_AML_C3_TEE_SUPPORT), y),$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_AMLTEE,$(1)) $(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_TEE,$(1)) $(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_OPTEE,$(1)))

	$(call KCONFIG_DISABLE_OPT_LIST,$(CUSTOMIZE_KERNEL_DISABLE_OPT_LIST),$(1))
	$(call KCONFIG_ENABLE_OPT_LIST,$(CUSTOMIZE_KERNEL_ENABLE_OPT_LIST),$(1))
	$(call KCONFIG_SET_OPT_LIST,$(CUSTOMIZE_KERNEL_SET_OPT_LIST),$(1))
endef

define AML_KERENL_DOORBELL # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_FREERTOS_C3,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_SCSI,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_VT,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_UNIX98_PTYS,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_MODULE_UNLOAD,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PINCTRL_MESON_C3,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_I2C_MESON,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_GPIO,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_AMLOGIC_MTD_NAND,$(1))
endef

################################################################################
#
#  Kernel Debug
#
################################################################################
define AML_KERENL_PAGE_TRACE_ENABLE # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_FTRACE_SYSCALLS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PAGE_TRACE,$(1))
endef

define AML_KERENL_ARM_PERF_ENABLE # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_KALLSYMS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_KALLSYMS_ALL,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_PERF_EVENTS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_PROFILING,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_HW_PERF_EVENTS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_KUSER_HELPERS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_KPROBES,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_UPROBES,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_HAVE_HW_BREAKPOINT,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_ARM_PMU,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_UPROBE_EVENTS,$(1))
endef

define AML_KERENL_DMC_ENABLE # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_DDR_TOOL,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_DDR_BANDWIDTH,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_DDR_BANDWIDTH_C3,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PAGE_TRACE,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_DMC_MONITOR,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_DMC_DEV_ACCESS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_DMC_MONITOR_C3,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_FTRACE_SYSCALLS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_KALLSYMS_ALL,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_VMAP,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_DMC_MONITOR_BREAK_GKI,$(1))
endef

define AML_KERENL_KALLSYMS_ENABLE # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_KALLSYMS,$(1))
endef

define AML_KERENL_DEBUGFS_ENABLE # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_DEBUG_FS,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_SLUB_DEBUG,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAGIC_SYSRQ,$(1))
endef

define AML_KERENL_KASAN_ENABLE # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_KASAN,$(1))
endef

define AML_KERENL_FTRACE_ENABLE # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_FTRACE,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_FUNCTION_GRAPH_TRACER,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_FUNCTION_TRACER,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_FTRACE_SYSCALLS,$(1))
	$(call AML_KERENL_DEBUGFS_ENABLE,$(1))
endef

define AML_KERNEL_DEBUG_ENABLE # (file)
	$(if $(filter $(BR2_AML_C3_DEBUG_AML_KALLSYMS), y),$(call AML_KERENL_KALLSYMS_ENABLE,$(1)))
	$(if $(filter $(BR2_AML_C3_DEBUG_PAGE_TRACE), y),$(call AML_KERENL_PAGE_TRACE_ENABLE,$(1)))
	$(if $(filter $(BR2_AML_C3_DEBUG_ARM_PERF), y),$(call AML_KERENL_ARM_PERF_ENABLE,$(1)))
	$(if $(filter $(BR2_AML_C3_DEBUG_AML_DMC), y),$(call AML_KERENL_DMC_ENABLE,$(1)))
	$(if $(filter $(BR2_AML_C3_DEBUG_AML_DEBUGFS), y),$(call AML_KERENL_DEBUGFS_ENABLE,$(1)))
	$(if $(filter $(BR2_AML_C3_DEBUG_AML_FTRACE), y),$(call AML_KERENL_FTRACE_ENABLE,$(1)))
	$(if $(filter $(BR2_AML_C3_DEBUG_AML_KASAN), y),$(call AML_KERENL_KASAN_ENABLE,$(1)))
endef

################################################################################
#
#  Filesystem Config
#
################################################################################
#EXT4
define AML_FS_EXT4_KCONFIG_SET_OPT # (value[m,y,n], file)
		$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_EXT4_FS,$(1),$(2))
		$(call KCONFIG_SET_BOOL_OPT,CONFIG_EXT4_USE_FOR_EXT2,$(1),$(2))
		$(call KCONFIG_SET_BOOL_OPT,CONFIG_EXT4_FS_POSIX_ACL,$(1),$(2))
		$(call KCONFIG_SET_BOOL_OPT,CONFIG_EXT4_FS_SECURITY,$(1),$(2))
endef
#SQUASHFS
define AML_FS_SQUASHFS_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_SQUASHFS,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_SQUASHFS_XATTR,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_SQUASHFS_ZSTD,$(1),$(2))
endef
#FAT
define AML_FS_FAT_KCONFIG_SET_OPT  # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_FAT_FS,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_VFAT_FS,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_MSDOS_FS,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_FAT_DEFAULT_UTF8,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_EXFAT_FS,$(1),$(2))
endef
#NTFS
define AML_FS_NTFS_KCONFIG_SET_OPT  # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_NTFS3_FS,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_NTFS_FS,$(1),$(2))
endef
#JFFS2
define AML_FS_JFFS2_KCONFIG_SET_OPT  # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_JFFS2_FS,$(1),$(2))
endef

#UBIFS
define AML_FS_UBIFS_KCONFIG_SET_OPT  # (value[m,y,n], file)
	$(call CONFIG_MTD_UBI,CONFIG_UBIFS_FS_ADVANCED_COMPR,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_UBIFS_FS,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_MTD_UBI,$(1),$(2))
endef

define AML_FS_CONFIG_SET_OPT # (value[m,y], file)
	$(if $(filter $(BR2_TARGET_ROOTFS_SQUASHFS), y),$(call AML_FS_SQUASHFS_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_FS_SQUASHFS_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_TARGET_ROOTFS_JFFS2), y),$(call AML_FS_JFFS2_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_FS_JFFS2_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_TARGET_ROOTFS_UBIFS), y),$(call AML_FS_UBIFS_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_FS_UBIFS_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_TARGET_ROOTFS_EXT2), y),$(call AML_FS_EXT4_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_FS_EXT4_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_AML_C3_BOOT_MEDIUM), SPI_NOR),$(call AML_FS_JFFS2_KCONFIG_SET_OPT,y,$(2)); \
		$(call AML_FS_SQUASHFS_KCONFIG_SET_OPT,y,$(2)))
	$(if $(filter $(BR2_AML_C3_BOOT_MEDIUM), SPI_NAND),$(call AML_FS_UBIFS_KCONFIG_SET_OPT,y,$(2)))
	$(if $(filter $(BR2_AML_C3_PLATFORM), C302X_EMMC),$(call AML_FS_EXT4_KCONFIG_SET_OPT,y,$(2)))
	$(if $(filter $(BR2_AML_C3_PLATFORM), C302X_N2_DoorBell C302X_N3_DoorBell),$(call AML_FS_SQUASHFS_KCONFIG_SET_OPT,y,$(2)))
endef

################################################################################
#
#  AML MODULE Config
#
################################################################################

### MEDIA ###
define AML_MEDIA_KCONFIG_SET_OPT # (value[m,y,n], file)
	#common
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_MEDIA_MODULE,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_ENABLE,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_COMMON,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_SW_SYNC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_MEDIA_VFM,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_VPU,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_CODEC_MM,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_RDMA,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_CANVAS,$(1),$(2))
	#ion
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_ION_DEV,$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_ION,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_ION_SYSTEM_HEAP,$(1),$(2))
	#video_processor
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_VIDEO_COMPOSER,$(2))
	#video_sink
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_VIDEO,$(1),$(2))
	#vout
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_VOUT,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_LCD,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_LCD_TABLET,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_LCD_EXTERN,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_BACKLIGHT,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_BL_EXTERN,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_VOUT_SERVE,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_VOUT_CLK_SERVE,$(1),$(2))
	#osd
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_FB,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_FB_OSD_SYNC_FENCE,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_FB_OSD_VSYNC_RDMA,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_FB_OSD2_ENABLE,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_MEDIA_FB_OSD2_CURSOR,$(1),$(2))
endef

### SPI FLASH ###
define AML_SPI_NAND_FLASH_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_NAND,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_MTD_SPI_NAND,$(1),$(2))
endef

define AML_SPI_NOR_FLASH_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_MTD_SPI_NOR,$(1),$(2))
endef

### ASOC ###
define AML_ASOC_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_SOUND,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_SND,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_SND_SOC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_SOC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_SOC_AUGE,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_SOC_COMMON,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_AMAUDIO,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_AUDIO_DSP,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_AUDIO_INFO,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_SOC_CODECS,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_CODEC_A1_ACODEC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_CODEC_DUMMY_CODEC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_CODEC_AMLT9015,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_SOC_AD82584F,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_SOC_TAS5707,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_CODEC_TL1_ACODEC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_SND_SOC_TLV320ADC3101,$(1),$(2))
endef

### CRYPTO ###
define AML_CRYPTO_KCONFIG_SET_OPT # (value[m,y,n], file)
    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_ECC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_ECDH,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_CCM,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_GCM,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_CTR,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_ECB,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_CMAC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_HMAC,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_GHASH,$(1),$(2))

	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_LIB_ARC4,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_DES,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_LIB_DES,$(1),$(2))

    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_AES,$(1),$(2))
    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_LIB_AES,$(1),$(2))

	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_LIB_SHA256,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_SHA256,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_SHA512,$(1),$(2))

    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_CRYPTO_DMA,$(1),$(2))
    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_GF128MUL,$(1),$(2))
    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_DRBG,$(1),$(2))
    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_DRBG_MENU,$(1),$(2))
    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_JITTERENTROPY,$(1),$(2))

    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_USER_API,$(1),$(2))
    $(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_USER_API_SKCIPHER,$(1),$(2))
endef

### INPHY ###
define AML_INPHY_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_MDIO_G12A,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_INPHY,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_MII,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_MDIO_BUS_MUX,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_PCS_XPCS,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_STMMAC_ETH,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_STMMAC_PLATFORM,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_DWMAC_MESON,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_DWMAC_DWC_QOS_ETH,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_ETH_PRIVE,$(1),$(2))
endef

### ADB ###
define AML_ADB_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_USB_SUPPORT,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_USB,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_USB_OTG,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_USB_XHCI_HCD,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_USB_GADGET,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_USB_CONFIGFS,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_USB_CONFIGFS_UEVENT,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_USB_CONFIGFS_F_FS,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_USB,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_COMMON_USB,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_USB_SUPPORT,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_CRG,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_USBPHY,$(1),$(2))
endef

### USB ###
define AML_USB_STORAGE_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(if $(filter $(BR2_AML_C3_ADB_SUPPORT), y),,$(call AML_ADB_KCONFIG_SET_OPT,$(1),$(2)))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_BLK_DEV_SD,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_USB_XHCI_PLATFORM,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_USB_STORAGE,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_USB_UAS,$(1),$(2))
endef

### WIFI ###
define AML_WIFI_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_MAC80211,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CFG80211,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CFG80211_WEXT,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_CFG80211_CERTIFICATION_ONUS,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_CFG80211_REQUIRE_SIGNED_REGDB,n,$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_AMLOGIC_WIRELESS,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_RFKILL,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_AMLOGIC_WIFI,$(1),$(2))
endef

### BLUETOOTH ###
define AML_BLUETOOTH_KCONFIG_SET_OPT # (value[m,y,n], file)
	$(if $(filter $(BR2_AML_C3_WIFI_SUPPORT), y),,$(call AML_WIFI_KCONFIG_SET_OPT,$(1),$(2)))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_BT_HCIUART,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_BT_HCIUART_SERDEV,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_BT_HCIUART_H4,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_BT,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_BT_BREDR,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_BT_LE,$(1),$(2))
endef

### DM-VERITY ###
define AML_DM_VERITY_KCONFIG_SET_OPT # (value[m,y,n], file)
# dm verity
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_MD,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_BLK_DEV_DM,$(1),$(2))
	$(call KCONFIG_SET_BOOL_OPT,CONFIG_DM_VERITY,$(1),$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_SHA1,y,$(2))
	$(call KCONFIG_SET_TRISTATE_OPT,CONFIG_CRYPTO_SHA256,y,$(2))
endef


define AML_KERNEL_MODULE_CONFIG_SET_OPT # (value[m,y], file)
	$(if $(filter $(BR2_AML_C3_PLATFORM), C308L),,$(call AML_CRYPTO_KCONFIG_SET_OPT,n,$(2)))
	$(if $(findstring NON, $(BR2_AML_C3_SECURITY_BOOT)),$(call AML_DM_VERITY_KCONFIG_SET_OPT,n,$(2)),$(call AML_DM_VERITY_KCONFIG_SET_OPT,$(1),$(2)))
	$(if $(filter $(BR2_AML_C3_ADB_SUPPORT), y),$(call AML_ADB_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_ADB_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_AML_C3_USB_SUPPORT), y),$(call AML_USB_STORAGE_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_USB_STORAGE_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_AML_C3_WIFI_SUPPORT), y),$(call AML_WIFI_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_WIFI_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_AML_C3_BT_SUPPORT), y),$(call AML_BLUETOOTH_KCONFIG_SET_OPT,$(1),$(2)),$(call AML_BLUETOOTH_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_PACKAGE_MBD_VPU), y),$(call AML_MEDIA_KCONFIG_SET_OPT,$(1),$(2)),
			$(call AML_MEDIA_KCONFIG_SET_OPT,n,$(2)) $(call AML_ASOC_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_AML_C3_BOOT_MEDIUM), SPI_NAND),$(call AML_SPI_NAND_FLASH_KCONFIG_SET_OPT,$(1),$(2)) $(call AML_SPI_NOR_FLASH_KCONFIG_SET_OPT,n,$(2)))
	$(if $(filter $(BR2_AML_C3_BOOT_MEDIUM), SPI_NOR),$(call AML_SPI_NOR_FLASH_KCONFIG_SET_OPT,$(1),$(2)) $(call AML_SPI_NAND_FLASH_KCONFIG_SET_OPT,n,$(2)))
endef
################################################################################
#
#  Kernel module build-in
#
################################################################################

define AML_KERENL_MODULE_ALWAYS_BUILD_IN # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_CPU_INFO,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_I2C_MESON,$(1))
endef

define AML_KERENL_RAMDISK_MODULE_BUILD_IN # (file)
	$(call KCONFIG_ENABLE_OPT,CONFIG_BLK_DEV_INITRD,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_GPIO,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PINCTRL_MESON_C3,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PWM_MESON,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_REGULATOR_PWM,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PWM,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_PM_DEVFREQ,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_MESON_CPUFREQ,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_EFUSE_UNIFYKEY,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_MMC_MESON_GX,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_SPI,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_MTD_COMMON,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_MTD_RESV,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_SPI_MESON_SPICC,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_SPI_MESON_SPIFC_V2,$(1))
endef

define AML_KERENL_VENDOR_MODULE_BUILD_IN # (file)
	$(if $(filter $(BR2_AML_C3_PLATFORM), C308L),
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_RESET_MESON,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_MHU_MBOX,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_GKI_TOOL,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PINCTRL_MESON_C2,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PINCTRL_MESON_A1,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_PM,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_GX_REBOOT,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_POWER,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_TEE,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_AMLTEE,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_OPTEE,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_COMMON_CLK,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_COMMON_CLK_C2,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_COMMON_CLK_C3,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_COMMON_CLK_A1,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_INPUT,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_HIFI4DSP,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_MESON_SARADC,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_IRBLASTER,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_JTAG_MESON,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_MFD,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_REGULATOR,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_RTC,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_USB_DWC3,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_USB_DWC3_OF_SIMPLE,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_USB_SUPPORT,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_USB_DWC_OTG_HCD,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_MFD_CORE,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_REALTEK_PHY,$(1))
		$(call KCONFIG_ENABLE_OPT,CONFIG_USB_XHCI_PLATFORM,$(1))
		$(call AML_ASOC_KCONFIG_SET_OPT,y,$(1)))

	$(call KCONFIG_DISABLE_OPT,CONFIG_AMLOGIC_MTD_NAND,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_AMLOGIC_THERMAL,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_DMABUF_HEAPS_SYSTEM,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_SIT,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_INET_TUNNEL,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_NET_IP_TUNNEL,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_AMLOGIC_HW_RANDOM_MESON,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_NLS_ISO8859_1,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_NLS_CODEPAGE_437,$(1))

	$(call AML_INPHY_KCONFIG_SET_OPT,y,$(1))
endef

define AML_KERENL_MODULE_BUILD_IN # (file)
	$(call AML_KERENL_RAMDISK_MODULE_BUILD_IN,$(1))
	$(call AML_KERENL_VENDOR_MODULE_BUILD_IN,$(1))
endef

################################################################################
#
#  Kernel DTS Overlay
#
################################################################################

ifeq ($(BR2_AML_C3_DTB_OVERLAY),y)
AML_C3_DTB_OVERLAY_PATCHS =
ifeq ($(BR2_AML_C3_DTB_OVERLAY_TEE),y)
AML_C3_DTB_OVERLAY_PATCHS += tee
endif
ifeq ($(BR2_AML_C3_DTB_OVERLAY_MBD_AUDIO),y)
AML_C3_DTB_OVERLAY_PATCHS += mbd_audio
endif
endif

ifeq ($(BR2_AML_C3_DTB_OVERLAY),y)
define AML_C3_LINUX_DTB_OVERLAY
        $(foreach overlay,$(1),\
                $(@D)/scripts/dtc/dtc -q -I dts -O dtb -o $(BINARIES_DIR)/$(overlay).dtbo $(AML_C3_ENV_SITE)/dtb_overlay/$(overlay).dtsi; \
                $(@D)/scripts/dtc/fdtoverlay -i $(2)/$(AML_DTBS) -o $(2)/$(AML_DTBS) $(BINARIES_DIR)/$(overlay).dtbo; \
        )
endef
endif