#!/bin/sh

PIDDIR=/var/run/thirdreality
VOICE_ASSISTANT_PIDFILE=$PIDDIR/voice-assistant.pid

DEVICE_CONF="/data/conf/device.json"

start_voice_assistant() {
    mkdir -p $PIDDIR
    SPK_NAME=$(jq -r '.device.name // "thirdreality-speaker"' "$DEVICE_CONF")
    python3 -m linux_voice_assistant --name "$SPK_NAME" --wake-model "okay_nabu" --debug &
    echo $! > $VOICE_ASSISTANT_PIDFILE
}

stop_voice_assistant() {
    [ -f $VOICE_ASSISTANT_PIDFILE ] && kill "$(cat $VOICE_ASSISTANT_PIDFILE)" 2>/dev/null && rm -f $VOICE_ASSISTANT_PIDFILE
}

restart() {
    stop_voice_assistant
    sleep 1
    start_voice_assistant
}

case "$1" in
    start)
        start_voice_assistant
    ;;
    stop)
        stop_voice_assistant
    ;;
    restart)
        restart
    ;;
    *) echo "Usage: $0 {start|stop|restart}" ;;
esac
