[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True

# Ignore missing stubs for modules without py.typed marker
[mypy-mpv.*]
ignore_missing_imports = True

[mypy-soundcard.*]
ignore_missing_imports = True

[mypy-aioesphomeapi.api_pb2]
ignore_missing_imports = True
allow_subclassing_any = True
disable_error_code = attr-defined
